import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateDatabase1711717737975 implements MigrationInterface {
    name = 'CreateDatabase1711717737975'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "events" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "body" jsonb NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE VIEW "customer_view" AS SELECT ("event"."body" ->> 'customer_id')::uuid AS "customer_id", ("event"."body" ->> 'user_id')::uuid AS "user_id" FROM (SELECT ("inner_event"."body" ->> 'customer_id')::uuid AS "customer_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body" FROM "events" "inner_event" WHERE ("inner_event"."type" IN ('customer:created','customer:updated','customer:snapshot')) GROUP BY "inner_event"."body" ->> 'customer_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","customer_view","SELECT (\"event\".\"body\" ->> 'customer_id')::uuid AS \"customer_id\", (\"event\".\"body\" ->> 'user_id')::uuid AS \"user_id\" FROM (SELECT (\"inner_event\".\"body\" ->> 'customer_id')::uuid AS \"customer_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\" FROM \"events\" \"inner_event\" WHERE (\"inner_event\".\"type\" IN ('customer:created','customer:updated','customer:snapshot')) GROUP BY \"inner_event\".\"body\" ->> 'customer_id') \"event\""]);
        await queryRunner.query(`CREATE VIEW "merchant_view" AS SELECT ("event"."body" ->> 'merchant_id')::uuid AS "merchant_id", ("event"."body" ->> 'user_id')::uuid AS "user_id" FROM (SELECT ("inner_event"."body" ->> 'merchant_id')::uuid AS "merchant_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body" FROM "events" "inner_event" WHERE ("inner_event"."type" IN ('merchant:created','merchant:updated','merchant:snapshot')) GROUP BY "inner_event"."body" ->> 'merchant_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","merchant_view","SELECT (\"event\".\"body\" ->> 'merchant_id')::uuid AS \"merchant_id\", (\"event\".\"body\" ->> 'user_id')::uuid AS \"user_id\" FROM (SELECT (\"inner_event\".\"body\" ->> 'merchant_id')::uuid AS \"merchant_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\" FROM \"events\" \"inner_event\" WHERE (\"inner_event\".\"type\" IN ('merchant:created','merchant:updated','merchant:snapshot')) GROUP BY \"inner_event\".\"body\" ->> 'merchant_id') \"event\""]);
        await queryRunner.query(`CREATE VIEW "moderator_view" AS SELECT ("event"."body" ->> 'moderator_id')::uuid AS "moderator_id", ("event"."body" ->> 'user_id')::uuid AS "user_id" FROM (SELECT ("inner_event"."body" ->> 'moderator_id')::uuid AS "moderator_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body" FROM "events" "inner_event" WHERE ("inner_event"."type" IN ('moderator:created','moderator:updated','moderator:snapshot')) GROUP BY "inner_event"."body" ->> 'moderator_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","moderator_view","SELECT (\"event\".\"body\" ->> 'moderator_id')::uuid AS \"moderator_id\", (\"event\".\"body\" ->> 'user_id')::uuid AS \"user_id\" FROM (SELECT (\"inner_event\".\"body\" ->> 'moderator_id')::uuid AS \"moderator_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\" FROM \"events\" \"inner_event\" WHERE (\"inner_event\".\"type\" IN ('moderator:created','moderator:updated','moderator:snapshot')) GROUP BY \"inner_event\".\"body\" ->> 'moderator_id') \"event\""]);
        await queryRunner.query(`CREATE VIEW "user_view" AS SELECT ("event"."body" ->> 'user_id')::uuid AS "user_id", ("event"."body" ->> 'first_name')::varchar AS "first_name", ("event"."body" ->> 'last_name')::varchar AS "last_name", ("event"."body" ->> 'email')::varchar AS "email" FROM (SELECT ("inner_event"."body" ->> 'user_id')::uuid AS "user_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body" FROM "events" "inner_event" WHERE ("inner_event"."type" IN ('user:created','user:updated','user:snapshot')) GROUP BY "inner_event"."body" ->> 'user_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","user_view","SELECT (\"event\".\"body\" ->> 'user_id')::uuid AS \"user_id\", (\"event\".\"body\" ->> 'first_name')::varchar AS \"first_name\", (\"event\".\"body\" ->> 'last_name')::varchar AS \"last_name\", (\"event\".\"body\" ->> 'email')::varchar AS \"email\" FROM (SELECT (\"inner_event\".\"body\" ->> 'user_id')::uuid AS \"user_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\" FROM \"events\" \"inner_event\" WHERE (\"inner_event\".\"type\" IN ('user:created','user:updated','user:snapshot')) GROUP BY \"inner_event\".\"body\" ->> 'user_id') \"event\""]);
        await queryRunner.query(`CREATE VIEW "offer_variant_price_view" AS SELECT ("event"."body" ->> 'offer_variant_id')::uuid AS "offer_variant_id", ("event"."body" ->> 'offer_variant_price_id')::uuid AS "offer_variant_price_id", ("event"."body" ->> 'token_id')::uuid AS "token_id", "event"."body" ->> 'amount' AS "amount" FROM (SELECT ("inner_event"."body" ->> 'offer_variant_price_id')::uuid AS "offer_variant_price_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body" FROM "events" "inner_event" WHERE ("inner_event"."type" IN ('offer:variant:price:created','offer:variant:price:updated','offer:variant:price:snapshot')) GROUP BY "inner_event"."body" ->> 'offer_variant_price_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","offer_variant_price_view","SELECT (\"event\".\"body\" ->> 'offer_variant_id')::uuid AS \"offer_variant_id\", (\"event\".\"body\" ->> 'offer_variant_price_id')::uuid AS \"offer_variant_price_id\", (\"event\".\"body\" ->> 'token_id')::uuid AS \"token_id\", \"event\".\"body\" ->> 'amount' AS \"amount\" FROM (SELECT (\"inner_event\".\"body\" ->> 'offer_variant_price_id')::uuid AS \"offer_variant_price_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\" FROM \"events\" \"inner_event\" WHERE (\"inner_event\".\"type\" IN ('offer:variant:price:created','offer:variant:price:updated','offer:variant:price:snapshot')) GROUP BY \"inner_event\".\"body\" ->> 'offer_variant_price_id') \"event\""]);
        await queryRunner.query(`CREATE VIEW "offer_variant_view" AS SELECT ("event"."body" ->> 'offer_id')::uuid AS "offer_id", ("event"."body" ->> 'offer_variant_id')::uuid AS "offer_variant_id", "event"."body" ->> 'title' AS "title", "event"."body" ->> 'description' AS "description" FROM (SELECT ("inner_event"."body" ->> 'offer_variant_id')::uuid AS "offer_variant_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body" FROM "events" "inner_event" WHERE ("inner_event"."type" IN ('offer:variant:created','offer:variant:updated','offer:variant:snapshot')) GROUP BY "inner_event"."body" ->> 'offer_variant_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","offer_variant_view","SELECT (\"event\".\"body\" ->> 'offer_id')::uuid AS \"offer_id\", (\"event\".\"body\" ->> 'offer_variant_id')::uuid AS \"offer_variant_id\", \"event\".\"body\" ->> 'title' AS \"title\", \"event\".\"body\" ->> 'description' AS \"description\" FROM (SELECT (\"inner_event\".\"body\" ->> 'offer_variant_id')::uuid AS \"offer_variant_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\" FROM \"events\" \"inner_event\" WHERE (\"inner_event\".\"type\" IN ('offer:variant:created','offer:variant:updated','offer:variant:snapshot')) GROUP BY \"inner_event\".\"body\" ->> 'offer_variant_id') \"event\""]);
        await queryRunner.query(`CREATE VIEW "offer_view" AS SELECT ("event"."body" ->> 'offer_id')::uuid AS "offer_id", ("event"."body" ->> 'user_id')::uuid AS "user_id", ("event"."body" ->> 'title') AS "title", ("event"."body" ->> 'description') AS "description" FROM (SELECT ("inner_event"."body" ->> 'offer_id')::uuid AS "offer_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body" FROM "events" "inner_event" WHERE ("inner_event"."type" IN ('offer:created','offer:updated','offer:snapshot')) GROUP BY "inner_event"."body" ->> 'offer_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","offer_view","SELECT (\"event\".\"body\" ->> 'offer_id')::uuid AS \"offer_id\", (\"event\".\"body\" ->> 'user_id')::uuid AS \"user_id\", (\"event\".\"body\" ->> 'title') AS \"title\", (\"event\".\"body\" ->> 'description') AS \"description\" FROM (SELECT (\"inner_event\".\"body\" ->> 'offer_id')::uuid AS \"offer_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\" FROM \"events\" \"inner_event\" WHERE (\"inner_event\".\"type\" IN ('offer:created','offer:updated','offer:snapshot')) GROUP BY \"inner_event\".\"body\" ->> 'offer_id') \"event\""]);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","offer_view","public"]);
        await queryRunner.query(`DROP VIEW "offer_view"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","offer_variant_view","public"]);
        await queryRunner.query(`DROP VIEW "offer_variant_view"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","offer_variant_price_view","public"]);
        await queryRunner.query(`DROP VIEW "offer_variant_price_view"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","user_view","public"]);
        await queryRunner.query(`DROP VIEW "user_view"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","moderator_view","public"]);
        await queryRunner.query(`DROP VIEW "moderator_view"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","merchant_view","public"]);
        await queryRunner.query(`DROP VIEW "merchant_view"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","customer_view","public"]);
        await queryRunner.query(`DROP VIEW "customer_view"`);
        await queryRunner.query(`DROP TABLE "events"`);
    }

}
