import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdatedArchivedFlag1716822795482 implements MigrationInterface {
    name = 'UpdatedArchivedFlag1716822795482'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","offer_variant_view","public"]);
        await queryRunner.query(`DROP VIEW "offer_variant_view"`);
        await queryRunner.query(`CREATE VIEW "offer_variant_view" AS SELECT ("event"."body" ->> 'offer_id')::uuid AS "offer_id", ("event"."body" ->> 'offer_variant_id')::uuid AS "offer_variant_id", "event"."body" ->> 'title' AS "title", "event"."body" ->> 'description' AS "description", ("event"."body" ->> 'archived')::bool AS "archived", "event"."created_at" AS "created_at" FROM (SELECT ("inner_event"."body" ->> 'offer_variant_id')::uuid AS "offer_variant_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body", MIN("inner_event"."created_at") AS "created_at" FROM (SELECT * FROM "events" "event" WHERE ("event"."type" IN ('offer:variant:created','offer:variant:updated','offer:variant:snapshot')) ORDER BY id ASC) "inner_event" GROUP BY "inner_event"."body" ->> 'offer_variant_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","offer_variant_view","SELECT (\"event\".\"body\" ->> 'offer_id')::uuid AS \"offer_id\", (\"event\".\"body\" ->> 'offer_variant_id')::uuid AS \"offer_variant_id\", \"event\".\"body\" ->> 'title' AS \"title\", \"event\".\"body\" ->> 'description' AS \"description\", (\"event\".\"body\" ->> 'archived')::bool AS \"archived\", \"event\".\"created_at\" AS \"created_at\" FROM (SELECT (\"inner_event\".\"body\" ->> 'offer_variant_id')::uuid AS \"offer_variant_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\", MIN(\"inner_event\".\"created_at\") AS \"created_at\" FROM (SELECT * FROM \"events\" \"event\" WHERE (\"event\".\"type\" IN ('offer:variant:created','offer:variant:updated','offer:variant:snapshot')) ORDER BY id ASC) \"inner_event\" GROUP BY \"inner_event\".\"body\" ->> 'offer_variant_id') \"event\""]);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","offer_variant_view","public"]);
        await queryRunner.query(`DROP VIEW "offer_variant_view"`);
        await queryRunner.query(`CREATE VIEW "offer_variant_view" AS SELECT ("event"."body" ->> 'offer_id')::uuid AS "offer_id", ("event"."body" ->> 'offer_variant_id')::uuid AS "offer_variant_id", "event"."body" ->> 'title' AS "title", "event"."body" ->> 'description' AS "description", "event"."body" ->> 'archived' AS "archived", "event"."created_at" AS "created_at" FROM (SELECT ("inner_event"."body" ->> 'offer_variant_id')::uuid AS "offer_variant_id", jsonb_recursive_mergeagg("inner_event"."body") AS "body", MIN("inner_event"."created_at") AS "created_at" FROM (SELECT * FROM "events" "event" WHERE ("event"."type" IN ('offer:variant:created','offer:variant:updated','offer:variant:snapshot')) ORDER BY id ASC) "inner_event" GROUP BY "inner_event"."body" ->> 'offer_variant_id') "event"`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","offer_variant_view","SELECT (\"event\".\"body\" ->> 'offer_id')::uuid AS \"offer_id\", (\"event\".\"body\" ->> 'offer_variant_id')::uuid AS \"offer_variant_id\", \"event\".\"body\" ->> 'title' AS \"title\", \"event\".\"body\" ->> 'description' AS \"description\", \"event\".\"body\" ->> 'archived' AS \"archived\", \"event\".\"created_at\" AS \"created_at\" FROM (SELECT (\"inner_event\".\"body\" ->> 'offer_variant_id')::uuid AS \"offer_variant_id\", jsonb_recursive_mergeagg(\"inner_event\".\"body\") AS \"body\", MIN(\"inner_event\".\"created_at\") AS \"created_at\" FROM (SELECT * FROM \"events\" \"event\" WHERE (\"event\".\"type\" IN ('offer:variant:created','offer:variant:updated','offer:variant:snapshot')) ORDER BY id ASC) \"inner_event\" GROUP BY \"inner_event\".\"body\" ->> 'offer_variant_id') \"event\""]);
    }

}
